# Generated by Django 4.0.2 on 2022-08-02 15:40

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='image',
            field=models.ImageField(upload_to=account.models.uplaod_lucation),
        ),
    ]
