# Generated by Django 4.0.2 on 2022-07-22 09:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Blog-image'),
        ),
    ]
