# Generated by Django 4.0.2 on 2022-10-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_acount_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
