# Generated by Django 4.0.2 on 2022-07-22 10:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_acount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
