# Generated by Django 4.0.2 on 2022-08-02 15:40

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to=Blog.models.uplaod_lucation),
        ),
    ]
