# Generated by Django 4.0.2 on 2022-07-22 09:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Brand-image'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Catagory-image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Product-image'),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Supplier-image'),
        ),
    ]
