# Generated by Django 4.0.2 on 2022-08-02 15:40

import MyStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to=MyStore.models.Brand_lucation),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(upload_to=MyStore.models.product_lucation),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=MyStore.models.uplaod_lucation),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='image',
            field=models.ImageField(upload_to='suplier'),
        ),
    ]
