# Generated by Django 4.0.2 on 2022-07-22 09:55

import MyStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0002_alter_brand_image_alter_catagory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to=MyStore.models.Brand_lucation),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(null=True, upload_to=MyStore.models.uplaod_lucation),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=MyStore.models.product_lucation),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='image',
            field=models.ImageField(null=True, upload_to='supplayer'),
        ),
    ]
