# Generated by Django 3.2.3 on 2021-06-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0003_auto_20210604_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
