# Generated by Django 4.0.2 on 2022-03-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0003_expense_supplier_brand_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wherehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lucation', models.TextField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyStore.product')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='wherehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyStore.wherehouse'),
        ),
    ]
