# Generated by Django 4.0.2 on 2022-10-21 20:46

import MyStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0003_product_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TESTIMONIALS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=MyStore.models.TESTIMONIALS_lucation)),
                ('slug', models.SlugField(unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
