# Generated by Django 4.0.2 on 2022-03-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0004_wherehouse_expense_wherehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='wherehouse',
            name='stack',
            field=models.IntegerField(null=True),
        ),
    ]
