# Generated by Django 4.0.2 on 2022-10-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0004_testimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='slug',
        ),
    ]
