# Generated by Django 4.0.2 on 2022-03-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0005_wherehouse_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wherehouse',
            name='lucation',
        ),
        migrations.AddField(
            model_name='wherehouse',
            name='status',
            field=models.CharField(choices=[('full', ' full'), ('empty', ' empty'), ('Partial\t', ' Partial\t'), ('Pending', ' Pending')], default='Partial', max_length=20),
        ),
        migrations.AlterField(
            model_name='wherehouse',
            name='product',
            field=models.TextField(),
        ),
    ]
