# Generated by Django 3.2.3 on 2021-06-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0005_auto_20210604_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', ' Created'), ('Paid', ' Paid'), ('Pinding', ' Pinding'), ('Shipped', ' Shipped'), ('Refunded', ' Refunded')], default='Created', max_length=20),
        ),
    ]
