# Generated by Django 4.0.2 on 2022-03-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0010_remove_wherehouse_product_remove_wherehouse_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wherehouse',
            old_name='transfere',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='transfere',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wherehouse_product', to='MyStore.wherehouse'),
        ),
    ]
