# Generated by Django 4.0.2 on 2022-03-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0011_rename_transfere_wherehouse_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfere',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyStore.product'),
        ),
    ]
