# Generated by Django 4.0.2 on 2022-03-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0012_alter_transfere_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfere',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wherehouse_product', to='MyStore.wherehouse'),
        ),
    ]
