# Generated by Django 4.0.2 on 2022-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0013_alter_transfere_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wherehouse',
            name='stack',
            field=models.IntegerField(default=0),
        ),
    ]
