# Generated by Django 4.0.2 on 2022-03-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0014_wherehouse_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wherehouse',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='wherehouse',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wherehouse',
            name='stack',
        ),
        migrations.AddField(
            model_name='transfere',
            name='stack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wherehouse',
            name='lucation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfere',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyStore.product'),
        ),
    ]
