# Generated by Django 4.0.2 on 2022-03-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0015_remove_wherehouse_date_add_remove_wherehouse_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('Shupping_Cost', models.IntegerField()),
                ('Document', models.FileField(upload_to='product/files')),
                ('stack', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyStore.product')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyStore.suplier')),
                ('wherehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyStore.wherehouse')),
            ],
        ),
    ]
