# Generated by Django 4.0.2 on 2022-03-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0016_suplier_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
